# Generated by Django 3.0.6 on 2020-07-18 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import subsites.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsite_name', models.CharField(max_length=50, null=True, verbose_name='Имя сайта')),
                ('subsite_slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('subsite_logo', models.ImageField(blank=True, null=True, unique=True, upload_to=subsites.models.logo_upload_to)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsites', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'категорию',
                'verbose_name_plural': 'категории',
                'ordering': ('-created_at',),
            },
        ),
    ]
