# Generated by Django 3.0.6 on 2020-07-18 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subsites', '0001_initial'),
        ('articles', '0005_auto_20200718_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='subsite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_subsites', to='subsites.Subsite', verbose_name='Подсайт'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
